#!/usr/bin/env python3
"""
Synthetic Data Generator for AI-Enabled Financial Data Platform PoC
Domain Alignment: BIAN / FIBO
Target Output: supabase/seed.sql
Generates:
  - Reference static tables (ref_currency, ref_country, ref_nace_industry)
  - 1,000 Core Parties (80% Individual, 20% Organization)
  - 1 to 5 product agreements per customer
  - SCD Type 2 multi-version historical records (~15-20% historical updates)
  - Edge cases: High AML risk, zero/negative balances, NPL defaults, multi-currency accounts
  - All tables strictly prefixed by Data Product name (ref_, party_, deposit_, loan_)
"""

import uuid
import random
from datetime import datetime, timedelta, date

# Set fixed seed for deterministic reproducibility
random.seed(42)

TOTAL_PARTIES = 1000
INDIVIDUAL_RATIO = 0.8  # 800 Individuals, 200 Organizations
SCD2_MUTATION_RATIO = 0.18  # 18% multi-version records

# Reference Data Sets
CURRENCIES = [
    ("USD", "US Dollar", "$", 2),
    ("EUR", "Euro", "€", 2),
    ("GBP", "British Pound", "£", 2),
    ("CHF", "Swiss Franc", "CHF", 2),
    ("JPY", "Japanese Yen", "¥", 0),
]

COUNTRIES = [
    ("US", "United States", "USA", "840", False),
    ("DE", "Germany", "DEU", "276", False),
    ("FR", "France", "FRA", "250", False),
    ("GB", "United Kingdom", "GBR", "826", False),
    ("JP", "Japan", "JPN", "392", False),
    ("CH", "Switzerland", "CHE", "756", False),
    ("KY", "Cayman Islands", "CYM", "136", True),   # High AML Risk
    ("PA", "Panama", "PAN", "591", True),           # High AML Risk
]

NACE_CODES = [
    ("K64.1.9", "K", "Financial Intermediation Services", "HIGH"),
    ("J62.0.1", "J", "Computer Programming & Tech Consulting", "LOW"),
    ("G47.1.1", "G", "Retail Sale in Non-Specialised Stores", "MEDIUM"),
    ("C10.1.1", "C", "Processing and Preserving of Meat", "MEDIUM"),
    ("F41.2.0", "F", "Construction of Residential Buildings", "HIGH"),
    ("M69.1.0", "M", "Legal and Accounting Services", "MEDIUM"),
    ("H51.1.0", "H", "Passenger Air Transport", "HIGH"),
]

FIRST_NAMES = ["Alexander", "Sophie", "Maximilian", "Emma", "Liam", "Olivia", "Noah", "Ava", "Ethan", "Isabella", 
               "Lucas", "Mia", "Benjamin", "Charlotte", "Oliver", "Amelia", "Henry", "Harper", "Sebastian", "Evelyn"]
LAST_NAMES = ["Mueller", "Smith", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Hoffmann",
              "Schulz", "Koch", "Bauer", "Richter", "Klein", "Wolf", "Schroeder", "Neumann", "Schwarz", "Zimmermann"]

ORG_PREFIXES = ["Global", "Apex", "Nexus", "Vertex", "Vanguard", "Horizon", "Quantum", "Synergy", "Pacific", "Atlantic"]
ORG_SUFFIXES = ["Technologies", "Logistics", "Investments", "Holdings", "Capital", "Solutions", "Industries", "Trading"]
LEGAL_FORMS = ["GmbH", "AG", "Inc.", "LLC", "Corp", "PLC", "S.A."]

STREETS = ["Hauptstrasse", "Market Street", "Wall Street", "Bahnhofstrasse", "Rue de Rivoli", "Oxford Street", "Kurfuerstendamm"]
CITIES = ["Frankfurt", "New York", "London", "Zurich", "Paris", "Tokyo", "Berlin", "Munich"]

# Helper SQL formatting functions
def esc(val):
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "TRUE" if val else "FALSE"
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, (datetime, date)):
        return f"'{val.isoformat()}'"
    clean_str = str(val).replace("'", "''")
    return f"'{clean_str}'"

def dt_str(dt):
    if dt is None:
        return "NULL"
    return f"'{dt.strftime('%Y-%m-%d %H:%M:%S+00')}'"

def date_str(d):
    if d is None:
        return "NULL"
    return f"'{d.strftime('%Y-%m-%d')}'"

def main():
    print("Generating Synthetic Data for AI-Enabled Financial Data Platform PoC...")

    sql_lines = []
    sql_lines.append("-- ============================================================================")
    sql_lines.append("-- Supabase Seed File: AI-Enabled Financial Data Platform Synthetic Seed")
    sql_lines.append("-- Auto-generated by scripts/generate_synthetic_data.py")
    sql_lines.append("-- Total Core Parties: 1,000 (80% Individual, 20% Organization)")
    sql_lines.append("-- Table Naming Rule: All table names strictly prefixed by Data Product name")
    sql_lines.append("-- ============================================================================\n")

    sql_lines.append("BEGIN;\n")

    # 1. REFERENCE SEED DATA
    sql_lines.append("-- ----------------------------------------------------------------------------")
    sql_lines.append("-- SECTION 1: REFERENCE TABLES")
    sql_lines.append("-- ----------------------------------------------------------------------------")
    for code, name, symbol, decimals in CURRENCIES:
        sql_lines.append(
            f"INSERT INTO ref.ref_currency (currency_code, currency_name, symbol, decimal_places) "
            f"VALUES ({esc(code)}, {esc(name)}, {esc(symbol)}, {decimals}) ON CONFLICT DO NOTHING;"
        )

    for code, name, a3, num, high_risk in COUNTRIES:
        sql_lines.append(
            f"INSERT INTO ref.ref_country (country_code, country_name, iso_alpha3, iso_numeric, is_high_risk_aml) "
            f"VALUES ({esc(code)}, {esc(name)}, {esc(a3)}, {esc(num)}, {esc(high_risk)}) ON CONFLICT DO NOTHING;"
        )

    for code, sec, title, risk in NACE_CODES:
        sql_lines.append(
            f"INSERT INTO ref.ref_nace_industry (nace_code, nace_section, nace_title, risk_level) "
            f"VALUES ({esc(code)}, {esc(sec)}, {esc(title)}, {esc(risk)}) ON CONFLICT DO NOTHING;"
        )
    sql_lines.append("\n")

    # Statistics Counters
    stats = {
        "parties_total": TOTAL_PARTIES,
        "individuals": 0,
        "organizations": 0,
        "customers": 0,
        "deposit_accounts": 0,
        "deposit_balances": 0,
        "deposit_transactions": 0,
        "loan_applications": 0,
        "loan_agreements": 0,
        "loan_repayment_schedules": 0,
        "loan_disbursements": 0,
        "loan_collaterals": 0,
        "scd2_historical_versions": 0,
        "high_aml_risk_count": 0,
        "npl_loan_count": 0,
        "zero_negative_balances": 0
    }

    sql_lines.append("-- ----------------------------------------------------------------------------")
    sql_lines.append("-- SECTION 2: PARTY DATA PRODUCT SEED")
    sql_lines.append("-- ----------------------------------------------------------------------------")

    base_time = datetime(2025, 1, 1, 0, 0, 0)

    for i in range(1, TOTAL_PARTIES + 1):
        party_id = str(uuid.uuid4())
        party_bk = f"PTY-{i:06d}"
        is_individual = (i <= TOTAL_PARTIES * INDIVIDUAL_RATIO)
        party_type = "INDIVIDUAL" if is_individual else "ORGANIZATION"
        
        has_scd2_history = (random.random() < SCD2_MUTATION_RATIO)

        created_at = base_time + timedelta(days=random.randint(0, 300))

        if has_scd2_history:
            hist_party_id = str(uuid.uuid4())
            hist_from = created_at
            hist_to = created_at + timedelta(days=random.randint(30, 120))
            
            sql_lines.append(
                f"INSERT INTO financial.party (party_id, party_bk, party_type, status_code, md_created_at_utc, md_updated_at_utc, md_valid_from_utc, md_valid_to_utc, md_is_active) "
                f"VALUES ('{hist_party_id}', {esc(party_bk)}, {esc(party_type)}, 'ACTIVE', {dt_str(hist_from)}, {dt_str(hist_to)}, {dt_str(hist_from)}, {dt_str(hist_to)}, FALSE);"
            )
            stats["scd2_historical_versions"] += 1
            valid_from = hist_to
        else:
            valid_from = created_at

        sql_lines.append(
            f"INSERT INTO financial.party (party_id, party_bk, party_type, status_code, md_created_at_utc, md_updated_at_utc, md_valid_from_utc, md_valid_to_utc, md_is_active) "
            f"VALUES ('{party_id}', {esc(party_bk)}, {esc(party_type)}, 'ACTIVE', {dt_str(created_at)}, {dt_str(valid_from)}, {dt_str(valid_from)}, '9999-12-31 23:59:59+00', TRUE);"
        )

        if is_individual:
            stats["individuals"] += 1
            first_name = random.choice(FIRST_NAMES)
            last_name = random.choice(LAST_NAMES)
            dob = date(random.randint(1960, 2004), random.randint(1, 12), random.randint(1, 28))
            gender = random.choice(["MALE", "FEMALE"])
            citizenship = random.choice(COUNTRIES)[0]
            tax_res = citizenship
            
            sql_lines.append(
                f"INSERT INTO financial.party_individual (party_id, first_name, last_name, date_of_birth, gender, citizenship_country_code, tax_residence_country_code, md_valid_from_utc) "
                f"VALUES ('{party_id}', {esc(first_name)}, {esc(last_name)}, {date_str(dob)}, {esc(gender)}, {esc(citizenship)}, {esc(tax_res)}, {dt_str(valid_from)});"
            )
        else:
            stats["organizations"] += 1
            legal_name = f"{random.choice(ORG_PREFIXES)} {random.choice(ORG_SUFFIXES)} {random.choice(LEGAL_FORMS)}"
            trade_name = legal_name.split()[0] + " Corp"
            reg_num = f"REG-{random.randint(100000, 999999)}"
            inc_date = date(random.randint(1995, 2020), random.randint(1, 12), random.randint(1, 28))
            inc_country = random.choice(COUNTRIES)[0]
            nace = random.choice(NACE_CODES)[0]
            lform = legal_name.split()[-1]

            sql_lines.append(
                f"INSERT INTO financial.party_organization (party_id, legal_name, trade_name, registration_number, incorporation_date, incorporation_country_code, nace_code, legal_form, md_valid_from_utc) "
                f"VALUES ('{party_id}', {esc(legal_name)}, {esc(trade_name)}, {esc(reg_num)}, {date_str(inc_date)}, {esc(inc_country)}, {esc(nace)}, {esc(lform)}, {dt_str(valid_from)});"
            )

        street = f"{random.choice(STREETS)} {random.randint(1, 150)}"
        city = random.choice(CITIES)
        postcode = f"{random.randint(10000, 99999)}"
        c_code = random.choice(COUNTRIES)[0]

        sql_lines.append(
            f"INSERT INTO financial.party_address (party_id, address_type, street_address, city, postal_code, country_code, md_valid_from_utc) "
            f"VALUES ('{party_id}', 'REGISTERED', {esc(street)}, {esc(city)}, {esc(postcode)}, {esc(c_code)}, {dt_str(valid_from)});"
        )

        id_type = "TAX_ID" if not is_individual else random.choice(["PASSPORT", "NATIONAL_ID", "TAX_ID"])
        id_num = f"ID-{random.randint(1000000, 9999999)}"
        sql_lines.append(
            f"INSERT INTO financial.party_identification (party_id, id_type, id_number, issuing_country_code, issue_date, md_valid_from_utc) "
            f"VALUES ('{party_id}', {esc(id_type)}, {esc(id_num)}, {esc(c_code)}, {date_str(date(2020, 1, 1))}, {dt_str(valid_from)});"
        )

        cust_id = str(uuid.uuid4())
        cust_num = f"CUST-{i:06d}"
        segment = "RETAIL" if is_individual else random.choice(["SME", "CORPORATE"])
        onboard_date = date(2025, 1, 1) + timedelta(days=random.randint(0, 100))
        
        is_high_aml = (random.random() < 0.05) or (c_code in ["KY", "PA"])
        aml_risk = "HIGH" if is_high_aml else random.choice(["LOW", "LOW", "MEDIUM"])
        if is_high_aml:
            stats["high_aml_risk_count"] += 1

        sql_lines.append(
            f"INSERT INTO financial.party_role_customer (party_role_customer_id, customer_number, party_id, customer_segment, onboarding_date, kyc_status, aml_risk_rating, md_valid_from_utc) "
            f"VALUES ('{cust_id}', {esc(cust_num)}, '{party_id}', {esc(segment)}, {date_str(onboard_date)}, 'VERIFIED', {esc(aml_risk)}, {dt_str(valid_from)});"
        )
        stats["customers"] += 1

        # ------------------------------------------------------------------------
        # PRODUCT AGREEMENTS (1 to 5 contracts per customer)
        # ------------------------------------------------------------------------
        num_contracts = random.randint(1, 5)

        for c_idx in range(num_contracts):
            curr_code = random.choice(CURRENCIES)[0]
            is_deposit = (random.random() < 0.6)

            if is_deposit:
                acc_id = str(uuid.uuid4())
                acc_num = f"ACC-{i:04d}-{c_idx+1:02d}"
                acc_type = random.choice(["CHECKING", "SAVINGS", "TERM_DEPOSIT"])

                sql_lines.append(
                    f"INSERT INTO financial.deposit_account (deposit_account_id, account_number, customer_id, currency_code, account_type, account_status, opened_date, md_valid_from_utc) "
                    f"VALUES ('{acc_id}', {esc(acc_num)}, '{cust_id}', {esc(curr_code)}, {esc(acc_type)}, 'ACTIVE', {date_str(onboard_date)}, {dt_str(valid_from)});"
                )
                stats["deposit_accounts"] += 1

                is_neg_bal = (random.random() < 0.08)
                if is_neg_bal:
                    cur_bal = round(random.uniform(-500.0, 0.0), 2)
                    avail_bal = cur_bal
                    stats["zero_negative_balances"] += 1
                else:
                    cur_bal = round(random.uniform(500.0, 75000.0), 2)
                    avail_bal = cur_bal

                sql_lines.append(
                    f"INSERT INTO financial.deposit_balance (deposit_account_id, currency_code, current_balance, available_balance, ledger_balance, accrued_interest, md_valid_from_utc) "
                    f"VALUES ('{acc_id}', {esc(curr_code)}, {cur_bal}, {avail_bal}, {cur_bal}, 0.00, {dt_str(valid_from)});"
                )
                stats["deposit_balances"] += 1

                tx_ref = f"TXN-{acc_num}-001"
                tx_amount = round(random.uniform(100.0, 5000.0), 2)
                sql_lines.append(
                    f"INSERT INTO financial.deposit_transaction (transaction_reference, deposit_account_id, currency_code, transaction_type, amount, booking_date, value_date, md_valid_from_utc) "
                    f"VALUES ({esc(tx_ref)}, '{acc_id}', {esc(curr_code)}, 'DEPOSIT', {tx_amount}, {dt_str(valid_from)}, {date_str(onboard_date)}, {dt_str(valid_from)});"
                )
                stats["deposit_transactions"] += 1

                rate = round(random.uniform(0.005, 0.045), 5)
                sql_lines.append(
                    f"INSERT INTO financial.deposit_interest_term (deposit_account_id, interest_rate, rate_type, accrual_frequency, effective_date, md_valid_from_utc) "
                    f"VALUES ('{acc_id}', {rate}, 'VARIABLE', 'DAILY', {date_str(onboard_date)}, {dt_str(valid_from)});"
                )

                if is_neg_bal or acc_type == "CHECKING":
                    sql_lines.append(
                        f"INSERT INTO financial.deposit_overdraft_facility (deposit_account_id, approved_limit, interest_rate_penalty, facility_status, granted_date, md_valid_from_utc) "
                        f"VALUES ('{acc_id}', 1000.0000, 0.12000, 'ACTIVE', {date_str(onboard_date)}, {dt_str(valid_from)});"
                    )

            else:
                app_id = str(uuid.uuid4())
                app_num = f"LAP-{i:04d}-{c_idx+1:02d}"
                req_amount = round(random.uniform(5000.0, 250000.0), 2)

                sql_lines.append(
                    f"INSERT INTO financial.loan_application (loan_application_id, application_number, customer_id, currency_code, requested_amount, application_status, credit_score, submission_date, md_valid_from_utc) "
                    f"VALUES ('{app_id}', {esc(app_num)}, '{cust_id}', {esc(curr_code)}, {req_amount}, 'APPROVED', {random.randint(600, 820)}, {date_str(onboard_date)}, {dt_str(valid_from)});"
                )
                stats["loan_applications"] += 1

                loan_id = str(uuid.uuid4())
                loan_num = f"LNR-{i:04d}-{c_idx+1:02d}"
                int_rate = round(random.uniform(0.035, 0.095), 5)
                term_m = random.choice([12, 24, 36, 60, 120, 360])
                mat_date = onboard_date + timedelta(days=term_m * 30)

                is_npl = (random.random() < 0.10)
                agreement_status = "DEFAULTED" if is_npl else "ACTIVE"
                if is_npl:
                    stats["npl_loan_count"] += 1

                sql_lines.append(
                    f"INSERT INTO financial.loan_agreement (loan_agreement_id, agreement_number, loan_application_id, customer_id, currency_code, principal_amount, interest_rate, term_months, agreement_status, is_npl, disbursement_date, maturity_date, md_valid_from_utc) "
                    f"VALUES ('{loan_id}', {esc(loan_num)}, '{app_id}', '{cust_id}', {esc(curr_code)}, {req_amount}, {int_rate}, {term_m}, {esc(agreement_status)}, {esc(is_npl)}, {date_str(onboard_date)}, {date_str(mat_date)}, {dt_str(valid_from)});"
                )
                stats["loan_agreements"] += 1

                inst_principal = round(req_amount / 12.0, 2)
                inst_interest = round((req_amount * int_rate) / 12.0, 2)
                due_d = onboard_date + timedelta(days=30)
                inst_status = "OVERDUE" if is_npl else "PAID"
                paid_amt = 0.0 if is_npl else (inst_principal + inst_interest)

                sql_lines.append(
                    f"INSERT INTO financial.loan_repayment_schedule (loan_agreement_id, installment_number, due_date, principal_due, interest_due, total_due, installment_status, paid_amount, md_valid_from_utc) "
                    f"VALUES ('{loan_id}', 1, {date_str(due_d)}, {inst_principal}, {inst_interest}, {inst_principal + inst_interest}, {esc(inst_status)}, {paid_amt}, {dt_str(valid_from)});"
                )
                stats["loan_repayment_schedules"] += 1

                disb_ref = f"DISB-{loan_num}-01"
                sql_lines.append(
                    f"INSERT INTO financial.loan_disbursement (disbursement_reference, loan_agreement_id, currency_code, disbursed_amount, disbursement_date, target_account_number, md_valid_from_utc) "
                    f"VALUES ({esc(disb_ref)}, '{loan_id}', {esc(curr_code)}, {req_amount}, {dt_str(valid_from)}, 'ACC-DISB-BENEFICIARY', {dt_str(valid_from)});"
                )
                stats["loan_disbursements"] += 1

                col_val = round(req_amount * 1.35, 2)
                sql_lines.append(
                    f"INSERT INTO financial.loan_collateral (loan_agreement_id, collateral_type, currency_code, estimated_value, ltv_ratio, valuation_date, md_valid_from_utc) "
                    f"VALUES ('{loan_id}', 'REAL_ESTATE', {esc(curr_code)}, {col_val}, 0.75000, {date_str(onboard_date)}, {dt_str(valid_from)});"
                )
                stats["loan_collaterals"] += 1

    sql_lines.append("\nCOMMIT;\n")

    seed_path = "supabase/seed.sql"
    with open(seed_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"Successfully generated synthetic seed file at: {seed_path}")
    print("=" * 65)
    print("SYNTHETIC DATA SUMMARY STATISTICS & CARDINALITY REPORT")
    print("=" * 65)
    for k, v in stats.items():
        print(f"  - {k:<30}: {v:>8}")
    print("=" * 65)

if __name__ == "__main__":
    main()
